version: '3.8'

services:
  server:
    restart: on-failure
    image: docker.io/ascold2017/sam-simulator-server
    hostname: server

  client:
    image: docker.io/ascold2017/sam-simulator-client
    ports:
      - "80:80"
    depends_on:
      - server
  
  
    